spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  cloud:
    nacos:
      config:
        enabled: ${SPRING_CLOUD_NACOS_CONFIG_ENABLED:false}
      discovery:
        enabled: ${SPRING_CLOUD_NACOS_DISCOVERY_ENABLED:false}

server:
  port: ${SERVER_PORT:8081}
